version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12.3

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install pip-tools

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Check requirements.txt consistency
          command: |
            . venv/bin/activate
            pip-compile --dry-run --output-file=- requirements.in | diff -u requirements.txt -

      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            pytest

      - run:
          name: Check Code Format with Black
          command: |
            . venv/bin/activate
            black --check .

workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build-and-test
