version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-cache-{{ checksum "requirements.txt" }}
            - v1-pip-cache-
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install pip-tools
      - save_cache:
          key: v1-pip-cache-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip
      - run:
          name: Check requirements.txt consistency
          command: |
            . venv/bin/activate
            pip-compile --no-header --strip-extras --output-file=requirements.txt.tmp requirements.in
            diff -u requirements.txt requirements.txt.tmp

  test:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-cache-{{ checksum "requirements.txt" }}
            - v1-pip-cache-
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            pytest -s tests

  lint:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-cache-{{ checksum "requirements.txt" }}
            - v1-pip-cache-
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Check Code Format with Black
          command: |
            . venv/bin/activate
            black --check .

workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
