version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12.3

    steps:
      - checkout

      - restore_cache:
          keys:
            # requirements.txtが変更されたらキャッシュを破棄
            - v1-pip-cache-{{ checksum "requirements.txt" }}
            # フォールバック用のキー
            - v1-pip-cache-

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install pip-tools

      - save_cache:
          key: v1-pip-cache-{{ checksum "requirements.txt" }}
          paths:
            # venvディレクトリではなく、pipのキャッシュディレクトリを保存
            - ~/.cache/pip

      - run:
          name: Check requirements.txt consistency
          command: |
            . venv/bin/activate
            # 一時ファイルに生成してから比較することで、ヘッダーの差分を防ぐ
            pip-compile --strip-extras --output-file=requirements.txt.tmp requirements.in
            diff -u requirements.txt requirements.txt.tmp

      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            # pytest を直接実行する例
            pytest -s tests

      - run:
          name: Check Code Format with Black
          command: |
            . venv/bin/activate
            # black を直接実行する例
            black .

workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build-and-test
