name: Lint (Black)

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install pip-tools
      run: pip install pip-tools

    - name: Compile requirements.txt
      run: pip-compile requirements.in

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Black
      run: black --check .
